### ISSUE TITLE
Validation schema for config

### ISSUE THREAD

**Issue by alutman-innablr** [Innablr/revolver#102]
The current config validation is minimal and done in pure script. It would be easier to keep the validation up to date with some sort of yaml schema, which should also provide more informative errors for users.

**Comment by simon-anz** [comment]
https://www.npmjs.com/package/yaml-validator ?

**Comment by simon-anz** [comment]
Zod looks cool
https://zod.dev/?id=basic-usage

**Comment by simon-anz** [comment]
This can also be used to apply defaults, so the code that uses the config doesn't need to include it.

**Comment by alutman-innablr** [comment]
Nice, suits perfectly. Though you'd want to parse the config after the defaults and account specific settings are merged.

Will be glad to remove the random default strings we have in code.

**Comment by lyricnz** [comment]
#123

**Comment by lyricnz** [comment]
@abukharov disagrees. wants freeform config, with no hard validation.

**Comment by lyricnz** [comment]
We should look at .passthrough() so that we can include unrecognised keys in the output object.
https://zod.dev/?id=passthrough

**Comment by alutman-innablr** [comment]
New requirement:
* Pass validation even if there are random blocks and fields. User should be able to fill YAML with stuff unrelated to Revolver and have it still load
* Still type the configuration on load and error if the revolver relevant config is wrong.

**Comment by lyricnz** [comment]
This should be as simple as changing:

```javascript
}).transform(config => {
```

to

```javascript
}).passthrough().transform(config => {
```

in config-schema.ts.  You still get typeful, validation, etc;  but also get the additional values.

**Comment by simon-anz** [comment]
@abukharov what was your expectation about _code_ being able to access new/nonschema configuration?  Are you expecting to be able _access_ these values, or just not-fail?

**Comment by alutman-innablr** [comment]
This is closeable now as we at least decided on having _a_ schema. Other notes can be new issues.
