### ISSUE TITLE
Support multiple file configuration.

### ISSUE THREAD

**Issue by alutman-innablr** [Innablr/revolver#104]
Any serious usage of revolver will end up needing a lot of configuration. We should support breaking the config in to multiple files (even if internally it treats it as one big one).

Options
* `import` statement in top level config to specify other files. Merge files together at the top level
* Directory specified that loads in all YAML (might want to tag the yaml with a generic `type: revolver` or something
* Explicit types of config. Configs are pasted together with custom logic and only contain specific data. Easier to handle priority and merge issues with this.

Considerations
* Arrays of data might be annoying to merge. e.g. accounts.includeList should merge things with the same account ID but this is an array.
* What takes priority and how deep should a merge go? Should a plugin default settings override at the top or try and merge each individual value underneath.

**Comment by lyricnz** [comment]
In meantime, this could be a preprocessing job, where script combines multiple files, applying some business validation (eg: account-id from directory, maximum priority, etc).

**Comment by lyricnz** [comment]
Probably solved by https://github.com/Innablr/revolver/pull/251
