### ISSUE TITLE
Clearer summary of the actions to be taken by a cycle of revolver

### ISSUE THREAD

**Issue by simon-anz** [Innablr/revolver#110]
At the moment, the logs are a mess of "has action but masked..."; "has action but in status..." etc

Please emit a summary/table of what's about to be done, just before it's run.  That's probably the only bit that operators are actually interested in.

**Comment by alutman-innablr** [comment]
Related: https://github.com/Innablr/revolver/issues/72

**Comment by alutman-innablr** [comment]
Fixed by PR
