### ISSUE TITLE
Support for custom/reusable schedule definitions

### ISSUE THREAD

**Issue by simon-anz** [Innablr/revolver#114]
It would be good if we could define (in config) a schedule:

Say:  afternoon_stuff = "Start=13:00|mon-fri;Stop=16:30|mon-fri;Override=Off"

Then attach "afternoon_stuff" to resources/central-config, rather than including the whole strong.  Similiar to the way in which "24x7" works.

**Comment by alutman-innablr** [comment]
Interim solution: YAML refs?
