### ISSUE TITLE
Ignore @aws-sdk package updates in dependabot

### ISSUE THREAD

**Issue by simon-anz** [Innablr/revolver#131]
Seems like new versions are released at least weekly - this is just unnecessary noise.

See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#ignore

**Comment by simon-anz** [comment]
This hasn't worked 
<img width="718" alt="image" src="https://github.com/Innablr/revolver/assets/69175652/a97d8af5-f97c-4e92-b2c6-524273dd33a3">

**Comment by lyricnz** [comment]
Still not working 🤯 

<img width="814" alt="image" src="https://github.com/Innablr/revolver/assets/122371/cf3fef02-37ed-41f3-8277-eb93919c56c1">

@alutman-innablr any idea?

**Comment by alutman-innablr** [comment]
They're minor version updates rather than patch.
https://github.com/Innablr/revolver/pull/194

**Comment by lyricnz** [comment]
Hopefully fixed this time :)
