### ISSUE TITLE
Expand documentation for central config plugin

### ISSUE THREAD

**Issue by alutman-innablr** [Innablr/revolver#141]
Current documentation is out of date and needs a step by step example

* How filters are applied.
* Tutorial from english requirements to long form
* From long form to short form
* Explain shorthand filters in more detail
* Several short examples with their english meaning

**Comment by simon-anz** [comment]
https://github.com/Innablr/revolver/issues/136

**Comment by alutman-innablr** [comment]
Closing. Addressed by https://github.com/Innablr/revolver/pull/154
