### ISSUE TITLE
Q: what are the "extra" nnn.revolver.js files in revolver.zip?

### ISSUE THREAD

**Issue by simon-anz** [Innablr/revolver#153]
What are the extra files, besides revolver.js?

```
❯ unzip -t revolver.zip
Archive:  revolver.zip
    testing: 584.revolver.js          OK
    testing: revolver.js              OK
    testing: 200.revolver.js          OK
    testing: revolver.js.LICENSE.txt   OK
    testing: 988.revolver.js          OK
    testing: 608.revolver.js          OK
    testing: 744.revolver.js          OK
    testing: 512.revolver.js          OK
No errors detected in compressed data of revolver.zip.
```

Why does the LICENSE file have such a strange name?

**Comment by simon-anz** [comment]
Probably related to https://github.com/Innablr/revolver/pull/91

**Comment by alutman-innablr** [comment]
LICENSE is generated by webpack, though it's copied over with the root LICENSE.
The others seem to be AWS code related to auth. I'll have a look at why they appear like this, is a little weird.

**Comment by lyricnz** [comment]
Was wondering why it has such a name?

{ from: 'LICENSE', to: 'revolver.js.LICENSE.txt' },

**Comment by alutman-innablr** [comment]
Files were webpack chunks, decided to limit it to a single chunk as there's nothing to optimize here for a lambda JS.


> Was wondering why it has such a name?
> 
> { from: 'LICENSE', to: 'revolver.js.LICENSE.txt' },

That's to override the license generated by webpack. It generates a default license with that name.
