### ISSUE TITLE
Implement linters/formatters in github workflows

### ISSUE THREAD

**Issue by lyricnz** [Innablr/revolver#18]
In order to keep the project style consistent, it would be useful to implement style checkers/formatters in github actions (and make these required for PR merges)

eg: megalinter https://github.com/marketplace/actions/megalinter

**Comment by lyricnz** [comment]
Looks like code already is setup for eslint which is one of the supported sub-systems in megalinter.

**Comment by lyricnz** [comment]
Good guide
https://nicolas.vuillamy.fr/improve-uniformize-and-secure-your-code-base-with-megalinter-62ebab422c1

**Comment by lyricnz** [comment]
Following errors were identified from `mega-linter-runner --flavor javascript`

Many of these checks may be unnecessary

<img width="1146" alt="image" src="https://github.com/Innablr/revolver/assets/122371/d1ecb82a-db0e-4f87-acd1-ac84e739003f">

**Comment by simon-anz** [comment]
eslint workflow added. Good enough for now.
