### ISSUE TITLE
Is Chai still the right testing framework/library?

### ISSUE THREAD

**Issue by lyricnz** [Innablr/revolver#186]
Just asking
https://blog.logrocket.com/comparing-best-node-js-unit-testing-frameworks/

Related https://github.com/Innablr/revolver/issues/82

**Comment by abukharov** [comment]
The testing framework we use is Mocha. On top of it Chai provides a neat assertion language, which makes test-cases a lot more comprehendable and functional. Even though Chai is not TS-native (neither is Mocha btw), it still has decent TS support. Alternatives for TS would pretty much only be Earl and assertive-ts, which are not nearly as functional as Chai. So unless there is a specific reason we want to get rid of Chai, I think the best choice is to keep it.
