### ISSUE TITLE
Allow use of tokens (eg date, time, etc) in output filenames

### ISSUE THREAD

**Issue by lyricnz** [Innablr/revolver#187]
Would be useful for allowing logs to be tracked over time

**Comment by simon-anz** [comment]
From README.md:

Note: if any of the file elements in resourceLog or auditLog contain tokens of the format: %xxxx these will be replaced by datetime tokens per https://moment.github.io/luxon/#/formatting?id=table-of-tokens. In this way, output files can be named uniquely based on the current datetime. For example:

      csv:
        file: 'resources.%yyyy%LL%dd.csv'
