### ISSUE TITLE
Lambda invocation of revolver is "success" even with multiple (quite serious) errors

### ISSUE THREAD

**Issue by simon-anz** [Innablr/revolver#198]
eg:

```
INFO 2024-02-20 02:27:39.484 ERROR /revolver.js:2 revolver:innovation Plugin powercycleCentral has invalid schedules "BusinessHours,EarlyStartBusinessHours,EarlyStartBusinessHours"

INFO	2024-02-20 02:27:39.485	ERROR	/revolver.js:2	revolver:accountRevolver	 Error  ENOENT: no such file or directory, open '/var/task/resources.json', -2, ENOENT, open, /var/task/resources.jsonerror stack: | 2024-02-20T02:27:39.485Z 0bd7819e-f232-40f8-b5cb-8159d426e0f8 INFO 2024-02-20 02:27:39.485 ERROR /revolver.js:2 revolver:accountRevolver Error ENOENT: no such file or directory, open '/var/task/resources.json', -2, ENOENT, open, /var/task/resources.json error stack:
-- | --

```

PS: why are messages both INFO and ERROR?

**Comment by lyricnz** [comment]
Raised issue about log format/content in cloudwatch in https://github.com/Innablr/revolver/issues/200

**Comment by abukharov** [comment]
Revolver normally does multiple things in multiple accounts and the fact that some accounts had invalid schedule settings should not cause a termination of the whole thing. 

The second error message is useless, it tells you that some file couldn't be open, but it doesn't elaborate on what this file is needed for, or what the administrator needs to do to solve the problem and why my resources are not getting powercycled.

The first INFO was added by Lambda, it will improve if we switch to JSON logging.

**Comment by simon-anz** [comment]
The second error is caused when Revolver attempts to write a local file, but uses '.' (which is probably read-only) rather than the ephemeral /tmp.  That isn't inside the scope of an account-operation - feels like it should be fatal, and/or cause nonzero exit.

**Comment by abukharov** [comment]
> feels like it should be fatal

This is probablty true, but no way you can deduce all that from the error message. That's why I'm saying we need to think through our logging better

**Comment by simon-anz** [comment]
Yes, I welcome your input - since you are most familiar with our current deployments.  All our recent changes are somewhat theoretical.

**Comment by lyricnz** [comment]
@abukharov perhaps we could collect/count log output at various levels, and return non-zero exit code if there is >0 log.error or log.fatal?

**Comment by abukharov** [comment]
Or create a global variable in logging.ts and set it to true/something else when a fatal or error happens. I think this would be a bit more elegant.

**Comment by abukharov** [comment]
and embed this logic into the logger itself

**Comment by abukharov** [comment]
Ah, this was what you actually suggested. I for some reason though that you were talking about parsing the resulting log files, sorry =)

Yeah, this may be a good idea.

**Comment by lyricnz** [comment]
Added a Logger class that trips when error/fatal messages are emitted:

```typescript
/**
 * A Logger that keeps track of whether a log of level 'error' or greater has been emitted.
 */
export class ErrorTrackingLogger<LogObj> extends Logger<LogObj> {
  public hasError = false;
  constructor(settings?: ISettingsParam<LogObj>, logObj?: LogObj) {
    super(settings, logObj);
    this.attachTransport((logObj) => {
      this.hasError = this.hasError || logObj._meta.logLevelId >= logLevels['error'];
    });
  }
}
```
