### ISSUE TITLE
Render a "nice view" of resources discovered, matched Matchers + Actions

### ISSUE THREAD

**Issue by simon-anz** [Innablr/revolver#202]
Continuing from the work started in https://github.com/Innablr/revolver/issues/181 and assuming that https://github.com/Innablr/revolver/issues/201 gets done, it would be nice to have a "report" on all resources found, states, actions, etc.   The JSON and CSV audit logs, and console logs, are not very "human friendly"

**Comment by lyricnz** [comment]
Would need some kind of template engine (like Jinja2 on python) which could work on the resources.json data. 
https://mozilla.github.io/nunjucks/ seems like a fairly direct port of Jinja2.

Either that or a more dynamic SPA that consumes the json file directly as a data source.

**Comment by simon-anz** [comment]
Basic solution in #219

**Comment by lyricnz** [comment]
https://github.com/Innablr/revolver/pull/223 close enough
