### ISSUE TITLE
Support for NOT modifying resources (Tags) in the target accounts

### ISSUE THREAD

**Issue by lyricnz** [Innablr/revolver#48]
This program needs the ability to not modify the target resources:
- adding comments about missing/malformed tags
- recording actions on resources
- stashing config values in tags to use for restore

The program should be able to run without these permissions.

This also means there needs to be enough logging to identify these situations in alerts/dashboards.

**Comment by simon-anz** [comment]
At the moment, if we ONLY use the central-config plugin (and not Redshift), it doesn't attempt to write any tags, so this kindof happens automatically.

**Comment by alutman-innablr** [comment]
Redshift driver performs some tagging in `start` and `stop` actions. These should be split in to separate tag resource actions if possible.

**Comment by simon-anz** [comment]
FYI Redshift not a requirement for CustomerA

**Comment by alutman-innablr** [comment]
Closing as central-config does this.
Redshift tagging issue here: https://github.com/Innablr/revolver/issues/155
