### ISSUE TITLE
When .ts files are deleted the .d.ts and .js files are left in filesystem

### ISSUE THREAD

**Issue by lyricnz** [Innablr/revolver#76]
Then checkout->install->build fails.  Is there a way to clean these before/during build? 
(this happened with recently-deleted rdsClusterSnapshot.ts rdsMultiAz*.ts etc)

**Comment by abukharov** [comment]
there's a 'clean' target for npm, that deletes .d.ts and .js files, but it doesn't work for dropped .ts sources, the only option is to delete them manually, do a `git reset --hard HEAD` or re-clone the repository.
