### ISSUE TITLE
Chai v5.0.0

### ISSUE THREAD

**Issue by lyricnz** [Innablr/revolver#82]
https://github.com/chaijs/chai/releases/tag/v5.0.0

Is chai-as-promised still needed? It hasn't been updated in 7 years..
https://www.npmjs.com/package/chai-as-promised?activeTab=versions

**Comment by simon-anz** [comment]
Dependabot found it https://github.com/Innablr/revolver/pull/83

**Comment by lyricnz** [comment]
And https://github.com/Innablr/revolver/pull/96

**Comment by abukharov** [comment]
> Is chai-as-promised still needed? It hasn't been updated in 7 years..

Without it Chai can not assert promises, which takes away a big chunk of its functionality. Chai-as-promised is pretty old, but there's no open CVEs against it, or other indication that it's insecure/obsolete.
