### ISSUE TITLE
Switch to API V3-style client calls to reduce bundled size.

### ISSUE THREAD

**Issue by lyricnz** [Innablr/revolver#86]
See https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/welcome.html#welcome_whats_new_v3_modularized_packages_code_size

The aws-sdk package adds about 40 MB to your application. Replacing var AWS = require("aws-sdk") with import {DynamoDB} from "@aws-sdk/client-dynamodb" reduces that overhead to about 3 MB. Restricting the import to just the DynamoDB client and ListTablesCommand command reduces the overhead to less than 100 KB.

**Comment by simon-anz** [comment]
https://aws.amazon.com/blogs/developer/modular-packages-in-aws-sdk-for-javascript/

**Comment by simon-anz** [comment]
Will need to update paginator pattern:
https://github.com/aws/aws-sdk-js-v3?tab=readme-ov-file#paginators
